2021/03/10/21:49:38 base_action.py INFO 点击元素('id', 'com.cuteu.videochat:id/btnTabMessage'),点击消息列表
2021/03/10/21:49:38 base_图失败
Traceback (most recent call last):action.py ERROR 当前网页截
  File "D:\po\base\base_action.py", line 64, in save_page_screenshot
    self.driver.get_screenshot_as_file(p_path.SCREENSHOTS_PATH+screenshot_path)
  File "d:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "d:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "d:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "d:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ScreenshotException: Message: Failed to capture a screenshot. Does the current view have 'secure' flag set?

